=== genome-vendor/ensembl/ensembl/docs/schema_description/schema_description.dtd
<!ELEMENT schemadescription (introduction?, diagram*, tablegroup*, concepts*)>
<!ATTLIST schemadescription schema-version CDATA #REQUIRED>
<!ATTLIST schemadescription document-version CDATA #REQUIRED>

<!ELEMENT introduction  (text, process?)>
<!ELEMENT text          (#PCDATA)>

<!ELEMENT process       (step*)>
<!ATTLIST process intro CDATA #IMPLIED>
<!ELEMENT step          (#PCDATA)>
<!ATTLIST step number   CDATA #REQUIRED>

<!ELEMENT concepts             (concept*)>
<!ELEMENT concept              (#PCDATA)>
<!ATTLIST concept  name        CDATA #REQUIRED>
<!ATTLIST concept  description CDATA #REQUIRED>

<!ELEMENT diagram               (#PCDATA)>
<!ATTLIST diagram url           CDATA #IMPLIED>
<!ATTLIST diagram description   CDATA #IMPLIED>

<!ELEMENT tablegroup             (table*)>
<!ATTLIST tablegroup name CDATA #REQUIRED>
<!ATTLIST tablegroup description CDATA #IMPLIED>

<!ELEMENT table         (name, description, used, see?)>
<!ELEMENT name          (#PCDATA)>
<!ELEMENT description   (#PCDATA)>
<!ELEMENT used          (#PCDATA)>
<!ELEMENT see           (tableref*, conceptref*, urlref*)>

<!ELEMENT tableref      (#PCDATA)>
<!ATTLIST tableref name   CDATA #IMPLIED>
<!ATTLIST tableref reason CDATA #IMPLIED>

<!ELEMENT conceptref      (#PCDATA)>
<!ATTLIST conceptref name   CDATA #IMPLIED>
<!ATTLIST conceptref reason CDATA #IMPLIED>

<!ELEMENT urlref        (#PCDATA)>
<!ATTLIST urlref name   CDATA #IMPLIED>
<!ATTLIST urlref reason CDATA #IMPLIED>
<!ATTLIST urlref url    CDATA #REQUIRED>

<!ELEMENT link          (#PCDATA)>
<!ATTLIST link name     CDATA #IMPLIED>
<!ATTLIST link url      CDATA #IMPLIED>

=== genome-vendor/ensembl/ensembl/docs/schema_description/tables.xml
<?xml version="1.0" standalone="no"?>

<?xml-stylesheet type="text/xsl" href="xml2html.xsl"?>

<!DOCTYPE schemadescription SYSTEM "schema_description.dtd">

<schemadescription schema-version="35" document-version="$Revision: 1.22 $">

  <introduction>
    <text>This document gives a high-level description of the tables that make up the EnsEMBL core schema. Tables are grouped into logical groups, and the purpose of each table is explained. It is intended to allow people to familiarise themselves with the schema when encountering it for the first time, or when they need to use some tables that they've not used before. Note that while some of the more important columns in some of the tables are discussed, this document makes no attempt to enumerate all of the names, types and contents of every single table. Some concepts which are referred to in the table descriptions are given at the end of this document; these are linked to from the table description where appropriate.</text>
    <process intro="Different tables are populated throughout the gene build process:">
      <step number="0">Create empty schema, populate meta table</step>
      <step number="1">Load DNA - populates dna, clone, contig, chromosome, assembly tables</step>
      <step number="2">Analyze DNA (raw computes) - populates genomic feature/analysis tables</step>
      <step number="3">Build genes - populates exon, transcript,etc. gene-related tables</step>
      <step number="4a">Analyze genes - populate protein_feature, xref tables, interpro</step>
      <step number="4b">ID mapping</step>
    </process>
  </introduction>
  
<!--
  <diagram url="http://www.sanger.ac.uk/Users/dta/schema/schema_a4.pdf" description="Schema diagram on 2 A4 pages for easy printing."/>
  <diagram url="http://www.sanger.ac.uk/Users/dta/schema/schema_a3.pdf" description="Schema diagram on one A3 page."/>
-->

  <tablegroup name="Fundamental tables" description="">
    
    <!-- ============================================================ -->

    <table>
      
      <name>seq_region</name>

      <description>Stores information about sequence regions. The primary key is used as a pointer into the dna table so that actual sequence can be obtained, and the coord_system_id allows sequence regions of multiple types to be stored. Clones, contigs and chromosomes are all now stored in the seq_region table. Contigs are stored with the co-ordinate system 'contig'. The relationship between contigs and clones is stored in the assembly table. The relationships between contigs and chromosomes, and between contigs and supercontigs, are stored in the assembly table. </description>
      
      <used></used>
      
      <see>
	<tableref name="dna" reason="1:1 relationship to the dna table."/>
	<tableref name="coord_system" reason="Describes which co-ordinates a particular feature is stored in."/>
      </see>

    </table>

    <!-- ============================================================ -->

    <table>
      
      <name>coord_system</name>

      <description>Stores information about the available co-ordinate systems for this species. Note that there must be one co-ordinate system that has the attribute "top_level" and one that has the attribute "sequence_level".</description>
      
      <used></used>
      
      <see>
	<tableref name="seq_region" reason="Has coord_system_id foreign key to allow joins with the coord_system table."/>
      </see>

    </table>
   
    <!-- ============================================================ -->

    <table>
      
      <name>seq_region_attrib</name>

      <description>Allows "attributes" to be defined for certain seq_regions. Provides a way of storing extra information about particular seq_regions without adding extra columns to the seq_region table. e.g. </description>
      
      <used></used>
      
      <see>
	<tableref name="seq_region" reason=""/>
	<tableref name="attrib_type" reason="Provides codes, names and desctriptions of attribute types."/>
      </see>

    </table>

    <!-- ============================================================ -->

    <table>
      
      <name>attrib_type</name>

      <description>Provides codes, names and desctriptions of attribute types.</description>
      
      <used></used>
      
      <see>
	<tableref name="seq_region_attrib" reason="Associates seq_regions with attributes."/>
      </see>

    </table>

    <!-- ============================================================ -->

    <table> 
      
      <name>dna</name>

      <description>Contains DNA sequence. This table has a 1:1 relationship with the contig table.</description>
      
      <used></used>

      <see>
	<tableref name="seq_region" reason="Relates sequence to features."/>
	<tableref name="external_synonym" reason="Allows xrefs to have more than one name"/>
      </see>

    </table>

    <!-- ============================================================ -->

    <table> 
      
      <name>dnac</name>

      <description>Stores compressed DNA sequence.</description>
      
      <used></used>

      <see>

      </see>

    </table>
    
    <!-- ============================================================ -->

    <table>
      
      <name>assembly</name>

      <description>Describes how contig sequences make up the chromosomal sequence. The data in this table defines the "static golden path", i.e. the best effort draft full genome sequence as determined by the UCSC or NCBI (depending which assembly you are using)  Each row represents a contig (raw_id, FK from contig table) at least part of  which is present in the golden path. The part of the contig that is in the path is delimited by fields raw_start and raw_end and the absolute position within the golden path chromosome (chromosome_id) is given by chr_start and chr_end. Each contig is in a "supercontig" such as a "fingerprint clone contig" or NT contig and the super contig is identified by the superctg_name column and the position of the specified section of the contig  within its supercontig is given by fields superctg_start and superctg_end. </description>
      
      <used></used>
      
      <see>
	<tableref name="seq_region" reason="Stores extra information about both the assembled object and its component parts"/>
	<conceptref name="supercontigs" reason="The mapping between contigs and supercontigs is also stored in the assembly table."/>
      </see>

    </table>

    <!-- ============================================================ -->

    <table>
      
      <name>assembly_exception</name>

      <description>Allows multiple sequence regions to point to the same sequence, analogous to a symbolic link in a filesystem pointing to the actual file. This mechanism has been implemented specifically to support haplotypes and PARs, but may be useful for other similar structures in the future.</description>
      
      <used></used>
      
      <see>
	<tableref name="assembly" reason=""/>
      </see>

    </table>

    <!-- ============================================================ -->

    <table>
      
      <name>karyotype</name>

      <description>Describes bands that can be stained on the chromosome.</description>
      
      <used></used>
      
      <see>
	
      </see>

    </table>

    <!-- ============================================================ -->

    <table>
      
      <name>exon</name>

      <description>Stores data about exons. Associated with transcripts via exon_transcript. Allows access to contigsseq_regions.</description>
      
      <used></used>
      
      <see>
	<tableref name="exon_transcript" reason="Used to associate exons with transcripts."/>
      </see>

    </table>

    <!-- ============================================================ -->

    <table>
      
      <name>exon_stable_id</name>

      <description>Relates exon IDs in this release to release-independent stable identifiers.</description>
      
      <used></used>
      
      <see>
	<conceptref name="stable_id" reason="Describes the rationale behind the use of stable identifiers."/>
      </see>

    </table>


    <!-- ============================================================ -->

    <table>
      
      <name>transcript</name>

      <description>Stores information about transcripts. Has seq_region_start, seq_region_end and seq_region_strand for faster retrieval and to allow storage independently of genes and exons. Note that a transcript is usually associated with a translation, but may not be, e.g. in the case of pseudogenes and RNA genes (those that code for RNA molecules).</description>
      
      <used></used>
      
      <see>
      </see>

    </table>

    <!-- ============================================================ -->

    <table>
      
      <name>transcript_stable_id</name>

      <description>Relates transcript IDs in this release to release-independent stable identifiers.</description>
      
      <used></used>
      
      <see>
	<conceptref name="stable_id" reason="Describes the rationale behind the use of stable identifiers."/>
      </see>

    </table>

    <!-- ============================================================ -->

    <table>
      
      <name>transcript_attrib</name>

      <description>Enables storage of attributes that relate to transcripts.</description>
      
      <used></used>
      
       <see>
	<tableref name="transcript" reason=""/>
      </see>

    </table>

    <!-- ============================================================ -->

    <table>
      
      <name>translation_attrib</name>

      <description>Enables storage of attributes that relate to translations.</description>
      
      <used></used>
      
       <see>
	<tableref name="translation" reason=""/>
      </see>

    </table>

    <!-- ============================================================ -->

    <table>
      
      <name>exon_transcript</name>
